Staging:
	name: Build and push the latest build to staging
	
	on:
	  push:
	    branches: [ main ]
	
	jobs:
	  build_push_image:
	    runs-on: ubuntu-latest
	
	    steps:
	      - uses: actions/checkout@v2
	      - name: Set up Docker Buildx
	        uses: docker/setup-buildx-action@v1
	      - name: Login to ACR
	        uses: docker/login-action@v1
	        with:
	          username: ${{ secrets.ACR_LOGIN }}
	          password: ${{ secrets.ACR_PASSWORD }}
	          registry: ${{ secrets.ACR_NAME }}
	      - name: Build and push Docker images
	        uses: docker/build-push-action@v2.2.1
	        with:
	          tags: ${{ secrets.ACR_NAME }}/contoso-website:latest
          push: true
