name: Build and push the tagged build to production

on:
  push:
    tags:
      - 'v*'
jobs:
  build_push_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ secrets.ACR_NAME }}/contoso-website

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ACR
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}
          registry: ${{ secrets.ACR_NAME }}

      - name: Build and push production image
        uses: docker/build-push-action@v2.2.1
        with:
          tags: ${{ steps.docker_meta.outputs.tags }}
          push: true
        labels: ${{ steps.docker_meta.outputs.labels }}
